//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtosalonDiplom.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avtomobili
    {
        public int IDAvto { get; set; }
        public string CarBrand { get; set; }
        public string ModelCar { get; set; }
        public Nullable<int> Cost { get; set; }
        public string YearAuto { get; set; }
        public string Color { get; set; }
        public string Country { get; set; }
        public string Complectation { get; set; }
        public string KPP { get; set; }
        public string Img { get; set; }
        public string KuzovType { get; set; }
        public string VIN { get; set; }
        public string DatePublic { get; set; }
        public string Description { get; set; }
        public string RegNumber { get; set; }
        public string EngineInfo { get; set; }
    }
}
