//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtosalonDiplom.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Avtosalon3Entities3 : DbContext
    {
        public Avtosalon3Entities3()
            : base("name=Avtosalon3Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avtomobili> Avtomobili { get; set; }
        public virtual DbSet<Klienti> Klienti { get; set; }
        public virtual DbSet<Prodazhi> Prodazhi { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Zayavki> Zayavki { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
